### ISSUE TITLE
Missing Street Names in Western Australia

### ISSUE THREAD

**Issue by jharpster** [Microsoft/Open-Maps#1]
# Task Description

This task includes identifying updating missing street names in Western Australia.  Improvements to the existing road network will include:

- Updating street names from official government sources
- Adding missing roads
- Correcting road alignment
- Improving road classification according to [local guidelines](http://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines)

## Sources

The State government agency of Western Australia has granted explicit permission to use road information from their public source to update OpenStreetMap. 

Feeds and shapefiles for the main road network (MRWA-514) are available [here](https://catalogue.data.wa.gov.au/dataset/ntwk-iris-road-network).  

The team will use all available imagery sources to help to confirm alignment of  streets. 
Identifying streets missing names can be done simply by using custom paint styles in JOSM. 

- [Streets Have No Names](https://josm.openstreetmap.de/josmfile?page=Styles/Noname&zip=1)
- [FIXME Highlights Warnings](https://josm.openstreetmap.de/josmfile?page=Styles/Fixme&zip=1)

## Changeset Comments
The team will use changeset comments consistent with [OSM Changeset Guidelines](http://wiki.openstreetmap.org/wiki/Good_changeset_comments)
The team will also include a source:name=* tag (i.e.=source:name=Main Roads Western Australia) so the source of the name is clear.

**Comment by andrewharvey** [comment]
> The team will use changeset comments consistent with OSM Changeset Guidelines
The team will also include a name:source=* tag (i.e.=data.wa.au.gov) so the source of the name is clear.

As pointed out at https://lists.openstreetmap.org/pipermail/talk-au/2017-December/011574.html, to be consistent with current tagging, it should be `source:name` and not `name:source`.

**Comment by FrakGart** [comment]
Mappers have been using source:name=Main Roads Western Australia:

https://taginfo.openstreetmap.org/tags/source%3Aname=Main%20Roads%20Western%20Australia

**Comment by jharpster** [comment]
Thanks for the feedback. I've updated the instructions.

**Comment by samwilson** [comment]
Some more discussion of this dataset here: http://www.openstreetmap.org/user/Sam%20Wilson/diary/40066

**Comment by jharpster** [comment]
Thanks @samwilson I hadn't seen that before. The road names seem pretty straight forward albeit with a lot of manual effort. I wonder if it would be worth trying to tackle mis-typed roads based on the MRWA-515. Our assumption is that folks on the ground have a better sense of what is unclassified, residential, arterial, etc than what we can infer off the satellite image or from the government source.

**Comment by samwilson** [comment]
Yes, I think there's a bunch of roads in that data, especially around smaller towns, that either don't yet exist or are just rough tracks; the data says they'd be residential. And alignments sometimes seem to differ, again often in more rural areas. Names though are pretty good (although, not on Rottnest so much — I hear that MRWA hasn't listened to the Rottnest Island Authority's attempts to correct things like *Kitson Point Road* → *Karlak Boodjar Road*; the latter is what's on the signs).
