### ISSUE TITLE
Missing Streets and Street Names in Australian Capital Territory (ACT)

### ISSUE THREAD

**Issue by kazale26** [Microsoft/Open-Maps#13]
# Task Description

This task includes identifying and updating missing streets and street names in Australian Capital Territory, Australia.  Improvements to the existing road network will include:

- Updating street names from official government sources
- Adding missing roads
- Correcting road alignment
- Improving road classification according to [local guidelines](http://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines)

## Sources

The State government agency of  Australian Capital Territory has granted [explicit permission](https://wiki.openstreetmap.org/wiki/Attribution/Australian_Capital_Territory) to use road information from their public source to update OpenStreetMap. 

The dataset used for editing is available  [here](http://actmapi-actgov.opendata.arcgis.com/datasets/26075cae1e5f4b77aece1ec8a3575846_1)

The team will use all available imagery sources to help to confirm alignment of  streets. 
Identifying streets missing names can be done simply by using custom paint styles in JOSM. 

- [Streets Have No Names](https://josm.openstreetmap.de/josmfile?page=Styles/Noname&zip=1)
- [FIXME Highlights Warnings](https://josm.openstreetmap.de/josmfile?page=Styles/Fixme&zip=1)

## Changeset Comments
The team will use changeset comments consistent with [OSM Changeset Guidelines](http://wiki.openstreetmap.org/wiki/Good_changeset_comments)
The team will also include source tags based on the [Tag:source=ACTMapiRoads](https://wiki.openstreetmap.org/wiki/Tag:source%3DACTMapiRoads) requirements from OSM Wiki

**Comment by andrewharvey** [comment]
The ACT 2017 Imagery was just added to the editor-layer-index via https://github.com/osmlab/editor-layer-index/pull/446 so should be in the next iD release or it can be added into JOSM as a new WMS Imagery source with `https://data.actmapi.act.gov.au/arcgis/services/actmapi/imagery2017mga/ImageServer/WMSServer?FORMAT=image/jpeg&amp;VERSION=1.1.1&amp;SERVICE=WMS&amp;REQUEST=GetMap&amp;LAYERS=0&amp;STYLES=&amp;SRS={proj}&amp;WIDTH={width}&amp;HEIGHT={height}&amp;BBOX={bbox}`

There will be newer 2018 imagery coming out in April.

The [OSMF CC BY waiver has also been completed](https://wiki.openstreetmap.org/wiki/File:ACT%20Government%2020180314%20Permission%20to%20Incorporate%20CCBY%20data%20into%20OSM.PDF) opening up all the CC BY licensed ACT Government foundational spatial datasets.
