### ISSUE TITLE
Surface Tags On Nodes

### ISSUE THREAD

**Issue by jharpster** [Microsoft/Open-Maps#17]
The team has found >5000  improperly surface=* tagged nodes in Australia. 
https://overpass-turbo.eu/s/ySQ

In each case we'll check to see if 

- The surface tag belongs on an adjacent way

- The node is representing something that might be more accurately represented by a closed or unclosed way (ie. parking)

- In other cases we'll just remove the surface tag from the node in alignment with guidelines on the [wiki](https://wiki.openstreetmap.org/wiki/Key:surface).

**Comment by jharpster** [comment]
@mvexel Wiki says surface tags should only be on ways. But your example is a good argument for the contrary.

**Comment by andrewharvey** [comment]
> The node is representing something that might be more accurately represented by a closed or unclosed way (ie. parking)

I suspect that's true for a lot of these, doesn't make it wrong, but if you're able to upgrade these to a way then :+1:

> In other cases we'll just remove the surface tag from the node in alignment with guidelines on the wiki.

I'd be cautious about that, always best to check with the original mapper before removing.

For example a lot of [traffic_calming](https://wiki.openstreetmap.org/wiki/Key:traffic_calming)'s should only be mapped as a node, and that node can have it's own surface.

**Comment by jharpster** [comment]
Good point on the traffic_calming @andrewharvey. We'll check with local mappers before completely removing tags , the intent is just to clean up some of the mess.

**Comment by BrackoNe** [comment]
Hi!

I have to be honest to say that I didn't get it completely.

"_For example a lot of traffic_calming's should only be mapped as a node, and that node can have it's own surface._" Partially correct. traffic_calming can be mapped as way as well (especially for traffic_calming=hump or traffic_calming=island).

If you look at https://wiki.openstreetmap.org/wiki/Key:surface, it is clear that surface tag can't be used as Property of node. It can be used for ways and areas (polygons).

However, if you scroll to **Values** section, you will see that surface key has plenty of varieties’. Just after that, there is **Element** column that says for every single value which type of element can be used. Anything except that is not allowed. There's no nodes at all.

Please confirm.

Nemanja

**Comment by bhousel** [comment]
It sounds like the team is planning to check each node to verify whether it is correctly tagged - this is good!

**The OSM Wiki is frequently wrong or offers contradictory advice,** as it's maintained by volunteers who often aren't working with the actual OSM data or tooling.  Anyway, it's important to view the wiki as a guide but not a spec.  The only true spec in OSM is the data itself. 

For example, things like [tennis courts](https://wiki.openstreetmap.org/wiki/Tag:sport=tennis) can be mapped as a point node with a surface tag.  This is fine.  Please don't remove the surface tags from them, just because you found a wiki page that says a wrong thing.

**Comment by andrewharvey** [comment]
> The OSM Wiki is frequently wrong or offers contradictory advice, as it's maintained by volunteers who often aren't working with the actual OSM data or tooling. Anyway, it's important to view the wiki as a guide but not a spec. The only true spec in OSM is the data itself.

:+1:

**Comment by BrackoNe** [comment]
Hello, thanks for supporting us and for your feedback @bhousel !

However I just want to say that your example confirms OSM Wiki again.
Sport (tennis court) can be marked as NODE or as AREA (polygon).
Surface can be used for WAYs or AREAs. So if sport (tennis) is marked as AREA, useful combination is surface. But users often do not read it carefuly, and it is like: "_Oh OK, I can mark as a node, and useful combination is surface. Great! I don't need anything else._"

I just wanted to emphasize that. I will not proceed with this task until I do not get green light.

**Comment by bhousel** [comment]
> Surface can be used for WAYs or AREAs.

@BrackoNe I am trying to be very nice here - the OSM wiki is not a spec.  It does not work the way you think it does.

> But users often do not read it carefuly, and it is like: "Oh OK, I can mark as a node, and useful combination is surface. Great! I don't need anything else."

Those users are correct.  There are situations where you can put a surface tag on a node.  The wiki page for surface is misleading.  Whoever wrote it was not thinking about point tagged things.  (parking lots, sports pitches, aerodromes, playgrounds).  You will find plenty when you start this task.

Please do not treat the OSM wiki as a spec.  Treat is as some person's opinion (and that person probably does not work on OSM tools or data).

**Comment by BrackoNe** [comment]
Thanks again for your reply!

> @BrackoNe I am trying to be very nice here - the OSM wiki is not a spec. It does not work the way you think it does.

Sure, I'm not yelling, just emphasizing types of entities, but I see that it would be better if I used bold function. :)

> Please do not treat the OSM wiki as a spec. Treat is as some person's opinion (and that person probably does not work on OSM tools or data).

OK, thanks for clarification. 👍
