### ISSUE TITLE
Fix Roundabouts in Australia

### ISSUE THREAD

**Issue by jharpster** [Microsoft/Open-Maps#19]
The team has  found about 90 instances of nodes with Junction tags to indicate a roundabout using this [Overpass query](https://overpass-turbo.eu/s/zVv).  

We will updates these to model them as proper roundabouts according to the [existing community guidelines](https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines#Roundabouts)

Before:
![beforeroundabout](https://user-images.githubusercontent.com/224853/42085781-2f69869e-7b46-11e8-9f36-58d0b45a0447.jpg)

After:

![afterroundabout](https://user-images.githubusercontent.com/224853/42085798-3907a000-7b46-11e8-8c52-f1abdb929e6d.jpg)

**Comment by zayuim** [comment]
I went and fixed the last 4 remaining. The overpass script turns up blank!

Australia is fixed :)
