### ISSUE TITLE
Missing One-Ways in Seattle

### ISSUE THREAD

**Issue by jharpster** [microsoft/Open-Maps#20]
The MS Open Maps team will work to add one ways and turn restrictions to improve the overall network in the Seattle area.

**Sources**:

- We are comparing the Seattle GIS Open data set against the current oneway=* attribution in OSM. The City of Seattle maintains a one-way dataset [here](https://data-seattlecitygis.opendata.arcgis.com/datasets/4d2400f72db04b55b8b8d5ddd9c2e343_1) which is Open and in a compatible license with OSM.

- The team will use both Mapillary & Bing Streetside imagery for validation.

**Scope of editing:**
The bulk of editing is adding one way attribution to the motorized road network. Additionally, the mappers will look at the attributes and classification of features they are editing.
Any others issues encountered will be resolved using the general and local guidelines outlined in the OSM Wiki, and USA guidelines.

**Validation:**
The team will using the built in validator in JOSM editor when uploading.

**Comment by TimuSumisu** [comment]
This project is no longer actively being worked on.
