### ISSUE TITLE
Missing Turn Restrictions in US Cities

### ISSUE THREAD

**Issue by jharpster** [Microsoft/Open-Maps#29]
## Task Description

This task includes identifying and updating missing turn restrictions in Boston. Improvements to the existing road network will include:

-   Updating street directionality (adding oneway tags)
-   Adding missing turn restrictions
-   Minor street alignments

### Sources

The team will be using signals based on Microsoft Streetide imagery that was processed by Mapbox to identify street signs indicating a possible turn restriction. (more info here: [mapbox/mapping#349](https://github.com/mapbox/mapping/issues/349))

The raw geojson of the street sign extractions are available on the Microsoft Open Maps [github repo here](https://github.com/Microsoft/Open-Maps/wiki/Streetside-Turn-Restrictions)

The team will also use all available imagery sources including Mapillary, OpenStreetCam and satellite to help to confirm directionality or turn restriction. In cases where the turn restriction cannot accurately be determined we will include a map note.

### Area of Focus

We are going to focus our efforts on the following cities in the US:

**Atlanta, Boston, Detroit, Denver, Chicago, Washington DC, Orlando, Miami, Phoenix, Portland OR, Philadelphia, Providence RI, New York City, Las Vegas, Los Angeles, Sacramento, San Francisco, Seattle, San Diego**

### Tools

We will be using [JOSM](https://josm.openstreetmap.de/) to do the adding and editing of roads. We will use our editing->validation->publication workflow to help ensure accuracy with two set of eyes on every edit.

Sources

-   DigitalGlobe Standard/Premium
-   Bing imagery
-   Mapbox imagery
-   ESRI imagery
-   Mapillary
-   OpenStreetCam
-   Bing Streetside and sign extractions
-   Tiger 2017,2018 road data

### Changeset Comments

The team will be adding changeset comments that follow [OSM changeset guidelines](http://wiki.openstreetmap.org/wiki/Good_changeset_comments).

### Error Detection

We will use the [validator](https://wiki.openstreetmap.org/wiki/JOSM/Validator) in the JOSM tool to look for errors.

### Additional Info

For any questions, comments, concerns, feel free to email the team at openmaps (at) microsoft.com

**Comment by jlevente** [comment]
Hey,

I just came across this OSM Note [1] that indicates that you guys might use Google Street View in addition to the data sources that you list on this page. Hopefully this is not the case but I wanted to double check. Can you please confirm that everyone on this team knows that the Google Street View is not compatible with OSM's ODbL license?

Cheers,
Levente

https://www.openstreetmap.org/note/1614829#map=19/25.75441/-80.20032&layers=N

**Comment by TimuSumisu** [comment]
Thanks for raising this up. Our policy for all editors strictly forbids use of Google streetview for any edits being made in OSM.
