### ISSUE TITLE
Maine Roads

### ISSUE THREAD

**Issue by jharpster** [microsoft/Open-Maps#38]
We will evaluate the use the Main roads dataset as a corroborating source for finding missing street names and one-ways for Main roads.
The dataset is maintained by the State [here](https://geolibrary-maine.opendata.arcgis.com/datasets/maine-e911-roads?geometry=-89.925%2C42.484%2C-48.089%2C47.897)

We will confirm the compatibility of the license for editing in OSM

**Comment by jharpster** [comment]
Misspelled Maine.

**Comment by TimuSumisu** [comment]
This project is no longer actively being worked on.
