### ISSUE TITLE
Vermont Roads

### ISSUE THREAD

**Issue by jharpster** [microsoft/Open-Maps#39]
We will evaluate the use the Vermont roads dataset as a corroborating source for finding missing street names and one-ways for Vermont roads.
The dataset is maintained by the State [here](http://geodata.vermont.gov/datasets/VTrans::vt-road-centerline)

We will confirm the compatibility of the license for editing in OSM

**Comment by TimuSumisu** [comment]
This project is no longer actively being worked on.
