### ISSUE TITLE
Missing Street Names in South Australia

### ISSUE THREAD

**Issue by jharpster** [Microsoft/Open-Maps#4]
# Task Description

This task includes identifying updating missing street names in South Australia.  Improvements to the existing road network will include:

- Updating street names from official government sources
- Adding missing roads
- Correcting road alignment
- Improving road classification according to [local guidelines](http://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines)

## Sources

The State government agency of South Australia has granted [explicit permission](https://wiki.openstreetmap.org/wiki/Contributors#South_Australian_Government_data) to use road information from their public source to update OpenStreetMap. 

Feeds and shapefiles for the main road network are available [here](https://data.sa.gov.au/data/dataset/roads).  

The team will use all available imagery sources to help to confirm alignment of  streets. 
Identifying streets missing names can be done simply by using custom paint styles in JOSM. 

- [Streets Have No Names](https://josm.openstreetmap.de/josmfile?page=Styles/Noname&zip=1)
- [FIXME Highlights Warnings](https://josm.openstreetmap.de/josmfile?page=Styles/Fixme&zip=1)

## Changeset Comments
The team will use changeset comments consistent with [OSM Changeset Guidelines](http://wiki.openstreetmap.org/wiki/Good_changeset_comments)
The team will also include a source:name=* tag (i.e.=data.sa.gov.au) so the source of the name is clear.

**Comment by BrackoNe** [comment]
We can use [TranistFeed](http://transitfeeds.com/search?q=australia) to _correct road types_ or even for _adding missing roads_.

Main idea was to download free, open Transit GTFS data and to make layer of it in any application (e.g. QGIS) and make conflation. After that we will be able to check whether roads are missing or not. Also, it is not usual that bus routes are going thru _[Street]_ (PROD's road type classification), but it's not a rule. I'm just saying that conflation can indicate if roads have lower road type classification then it should have.

Hope it helps,
Nemanja

**Comment by andrewharvey** [comment]
> The team will use changeset comments consistent with OSM Changeset Guidelines
The team will also include a name:source=* tag (i.e.=data.sa.gov.au) so the source of the name is clear.

As pointed out at https://lists.openstreetmap.org/pipermail/talk-au/2017-December/011574.html, to be consistent with current tagging, it should be `source:name` and not `name:source`.

**Comment by andrewharvey** [comment]
> We can use TranistFeed to correct road types or even for adding missing roads.
> 
>Main idea was to download free, open Transit GTFS data and to make layer of it in any application (e.g. QGIS) and make conflation. After that we will be able to check whether roads are missing or not. Also, it is not usual that bus routes are going thru [Street] (PROD's road type classification), but it's not a rule. I'm just saying that conflation can indicate if roads have lower road type classification then it should have.

@BrackoNe You can probably get away with doing that to make a list of places to further survey on the ground or check from other sources like aerial imagery, but since most of the GTFS feeds are CC BY licensed and you need the OSMF waiver completed to used CC BY data in OSM, you shouldn't be using most GTFS feeds as your main source of determining missing roads.

**Comment by BrackoNe** [comment]
OK, just to clarify. I should not use any GTFS feed without explicit right? I do not have any written permissions from any of GTFS providers.

**Comment by andrewharvey** [comment]
It really depends on the licensing of the GTFS data, as far as I'm aware all the open data GTFS feeds in AU are CC BY licensed, in fact pretty much all Australian data is licensed this way.

Since OSM changed it's license from CC-BY-SA to ODbL and CC BY isn't compatible with ODbL we need the OSMF CC BY waiver's completed or similar permissions to use CC BY data in OSM as noted at https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/.

**Comment by andrewharvey** [comment]
@BrackoNe We now have a blanket data.sa.gov.au CC BY 4.0 OSM waiver at https://wiki.openstreetmap.org/wiki/File:Data.sa.gov.au_CCBYPermission_Open_Street_Map.pdf

That covers the roads dataset @jharpster linked to and the Adelaide Metro GTFS feed https://data.sa.gov.au/data/dataset/adelaide-metro-general-transit-feed, plus a bunch of other datasets (relevant ones are listed at https://wiki.openstreetmap.org/wiki/Australian_Data_Catalogue under SA)

**Comment by BrackoNe** [comment]
Sounds great! However, we have higher priority tasks now, so it will wait for now.
