### ISSUE TITLE
US Road Names

### ISSUE THREAD

**Issue by TimuSumisu** [microsoft/Open-Maps#41]
Task summary:
This task includes identifying updating missing street names/missing named streets nationwide in the USA. Improvements to the existing road network will include:
•	Updating street names from official government sources (City, County, or State level)
•	Adding missing named roads.
•	Adding names to already mapped, but unnamed roads.
•	Correcting road alignment.
•	Add unpaved surface tags where necessary.

Sources:
Government agencies on a City/County/State granted permission to use road information from their public source to update OpenStreetMap.
We will also refer to TIGER 2018, and aerial imagery to confirm primary government source.

The team will use changeset comments consistent with [OSM Changeset Guidelines](https://wiki.openstreetmap.org/wiki/Good_changeset_comments).

**Comment by iandees** [comment]
It'd be really cool if you could share the data you're usinn for the road names. I built the TIGER 2018 layer and would like to to improve it to compare against more local data than TIGER.

**Comment by TimuSumisu** [comment]
This project is no longer actively being worked on. We'll be more thorough with our sources in project definitions in the future.
