### ISSUE TITLE
Missing Street Names in Townsville, QLD, Australia

### ISSUE THREAD

**Issue by BrackoNe** [microsoft/Open-Maps#43]
### Task Description
This task includes identifying updating missing street names in Townsville, QLD, Australia. Improvements to the existing road network will include:

- Updating street names from official government sources
- Adding missing roads
- Correcting road alignment

No road classification changes will be made.

### Sources
The City of Townsville has [granted explicit permission](https://wiki.openstreetmap.org/wiki/File:CCBY_Permission_Open_Street_Map-townsville.pdf) to use road information from their public source to update OpenStreetMap. 

We have run diff between unnamed roads/missing roads and Townsville Road Centerlines data set.

The team will use all available imagery sources to help to confirm alignment of streets. We could recognize that Maxar Premium Imagery is the latest imagery at the moment.

[Townsville Road Centerlines](https://data.gov.au/data/dataset/08ee44af-cdc4-4e4c-8ddb-186026b2207d)

### Changeset Comments
The team will also include a source:name=* tag (i.e.=data.gov.au) so the source of the name is clear.

**Comment by TimuSumisu** [comment]
This project is no longer actively being worked on.
