### ISSUE TITLE
Missing Street Names in Noosa, QLD, Australia

### ISSUE THREAD

**Issue by BrackoNe** [microsoft/Open-Maps#44]
### Task Description
This task includes identifying updating missing street names in area of Noosa, QLD, Australia. Improvements to the existing road network will include:

- Updating street names from official government sources
- Adding missing roads
- Minor correction of road alignment

No road classification changes will be made.

### Sources
The Noosa Shire Council has [granted explicit permission](https://wiki.openstreetmap.org/wiki/File:AU_Noosa_CCBY_Waiver.pdf) to use road information from their public source to update OpenStreetMap. 

We have run diff between unnamed roads/missing roads and Noosa Road Centerlines GeoJSON data set.

The team will use all available imagery sources to help to confirm alignment of streets. We could recognize that Bing Imagery is the latest imagery at the moment for given area.

[Noosa Road Centerlines GeoJSON](https://data.gov.au/dataset/ds-dga-560d5000-deec-45ce-a684-e07e4c566072/distribution/dist-dga-11f78a9d-0b70-4e18-baa6-153d13e0b965/details?q=road)

### Changeset Comments
The team will provide following description:
Adding missing roads from aerial imagery, and names from source=data.gov.au/ #maproulette

### Task
[MapRoulette task: QLD Noosa road centerlines](https://maproulette.org/challenge/11617/)

**Comment by TimuSumisu** [comment]
This project is no longer actively being worked on.
