### ISSUE TITLE
Speed limits in Australia

### ISSUE THREAD

**Issue by BrackoNe** [microsoft/Open-Maps#47]
We are adding missing speed limits at all secondary and higher classified roads. We will focus on all 70-110/130 kph speed limits.

Source for these speed limits primarly will be Mapillary, but OpenStreetCam will be used in case of lack of coverage.

Done so far: VIC, NT, TAS.
To complete: QLD, SA, WA and NSW.

**Comment by andrewharvey** [comment]
There is https://opendata.transport.nsw.gov.au/dataset/speed-zones which has data for NSW and we have a waiver. If you wanted to use this data, in my view these criteria would need to be met first:

- [ ] consult with `talk-au` about the plans and gather any feedback
- [ ] document if [source:maxspeed](https://wiki.openstreetmap.org/wiki/Key:source:maxspeed) will be included or not
- [ ] document what will be done if this data differs with whats in OSM or Mapillary
- [ ] ensure the source is tagged so we can see which data came from where
- [ ] ensure any plans include correct tagging of school zones and other conditional speed limits which are present in the data
- [ ] Update the contributors page to include the attribution for this dataset

**Comment by eneerhut** [comment]
New imagery being uploaded in [this small area](https://www.mapillary.com/app/user/assetsweddin?lat=20&lng=0&z=1.5&pKey=1bkRvlcqbSpyWz4bEGkIzj) of NSW around Grenfell. Likely a lot of new speed-limits for you.

Also worth checking out [new Port Adelaide imagery here](https://www.mapillary.com/app/user/portenf?lat=-34.85558095133333&lng=138.55650474333333&z=17&pKey=wteUFp4rsJ2D36Kb9DzRPx).

**Comment by andrewharvey** [comment]
>￼ document if source:maxspeed will be included or not

per some discussion on #nsw in maptime oceania slack, need to determine if we opt into [source:maxspeed](https://wiki.openstreetmap.org/wiki/Key:source:maxspeed) or [maxspeed:type](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type). Different regions use them differently eg https://wiki.openstreetmap.org/wiki/Key:source:maxspeed#United_Kingdom

**Comment by BrackoNe** [comment]
Hello!

I'm glad that this is on your radar now!
For now, we have resources only to process Mapillary/OSC indicators (because we have a visual confirmation), and we are processing all speed limits that are 70kph+ on a roads which are secondary and above.

There are no school zones, since these are mostly interconnecting roads between cities, and rarely in urban areas.

As we are adding speed limits only, Mapillary as a source is indicated in description of the changeset.

Very Best Regards,
Nemanja

**Comment by GenericError** [comment]
> > ￼ document if source:maxspeed will be included or not
> 
> per some discussion on #nsw in maptime oceania slack, need to determine if we opt into [source:maxspeed](https://wiki.openstreetmap.org/wiki/Key:source:maxspeed) or [maxspeed:type](https://wiki.openstreetmap.org/wiki/Key:maxspeed:type). Different regions use them differently eg https://wiki.openstreetmap.org/wiki/Key:source:maxspeed#United_Kingdom

> As we are adding speed limits only, Mapillary as a source is indicated in description of the changeset.

That's good to identify the source, but I have seen several edits that do not specify the **type of speed limit** - whether it be through a sign or the default AU:urban/AU:rural limits. Anything that isn't 50 or 100 will have to be a sign, which I *personally* think should be done with `maxspeed:type` and then put mapillary or the source in `source:maxspeed` or the changeset source

**Comment by BrackoNe** [comment]
We finished adding missing speed limits in AU. All roads higher then secondary, and speed limits higher then 70kph are added where we had visual confirmation on Mapillary or OSC.
