### ISSUE TITLE
Mistagged Water Features in Australia

### ISSUE THREAD

**Issue by jharpster** [Microsoft/Open-Maps#5]
There are a number of water features with more than one incompatible tag. These are mostly small reservoirs (landuse=reservoir) with an additional waterway=river or water=lake tag. These are small and easy to clean up. 

Using the list below remove the incompatible tag. Use the underlying imagery to improve the accuracy of the water if necessary. 

http://www.openstreetmap.org/way/218035341
http://www.openstreetmap.org/way/218035344
http://www.openstreetmap.org/way/218035349
http://www.openstreetmap.org/way/218035350
http://www.openstreetmap.org/way/218036594
http://www.openstreetmap.org/way/218036595
http://www.openstreetmap.org/way/218036598
http://www.openstreetmap.org/way/218036600
http://www.openstreetmap.org/way/218036602
http://www.openstreetmap.org/way/218036607
http://www.openstreetmap.org/way/218036608
http://www.openstreetmap.org/way/218036609
http://www.openstreetmap.org/way/218036611
http://www.openstreetmap.org/way/218036613
http://www.openstreetmap.org/way/218036614
http://www.openstreetmap.org/way/218036616
http://www.openstreetmap.org/way/218036621
http://www.openstreetmap.org/way/218036622
http://www.openstreetmap.org/way/218036625
http://www.openstreetmap.org/way/218036632
http://www.openstreetmap.org/way/218036633
http://www.openstreetmap.org/way/218036635
http://www.openstreetmap.org/way/218036636
http://www.openstreetmap.org/way/218036640
http://www.openstreetmap.org/way/218036643
http://www.openstreetmap.org/way/218036644
http://www.openstreetmap.org/way/218036646
http://www.openstreetmap.org/way/218036647
http://www.openstreetmap.org/way/218036649
http://www.openstreetmap.org/way/218036653
http://www.openstreetmap.org/way/218036658
http://www.openstreetmap.org/way/218036663
http://www.openstreetmap.org/way/218036664
http://www.openstreetmap.org/way/218036669
http://www.openstreetmap.org/way/218036670
http://www.openstreetmap.org/way/218036672
http://www.openstreetmap.org/way/218036675
http://www.openstreetmap.org/way/218036679
http://www.openstreetmap.org/way/263138439
http://www.openstreetmap.org/way/305377750
http://www.openstreetmap.org/way/314386142
http://www.openstreetmap.org/way/317002404
http://www.openstreetmap.org/way/320771765
http://www.openstreetmap.org/way/320771766
http://www.openstreetmap.org/way/320771767
http://www.openstreetmap.org/way/320771768

**Comment by BrackoNe** [comment]
Please notice that this task is completed.
