### ISSUE TITLE
Missing Street Names in New South Wales

### ISSUE THREAD

**Issue by jharpster** [Microsoft/Open-Maps#6]
# Task Description

This task includes identifying updating missing street names in New South Wales, Australia.  Improvements to the existing road network will include:

- Updating street names from official government sources
- Adding missing roads
- Correcting road alignment
- Improving road classification according to [local guidelines](http://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines)

## Sources

The State government agency of New South Wales has granted [explicit permission](https://wiki.openstreetmap.org/wiki/Attribution/New_South_Wales_Government_Data) to use road information from their public source to update OpenStreetMap. 

A web service to be used as a backdrop for editing is available  [here](http://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Base_Map/MapServer).  

This [Overpass query](https://overpass-turbo.eu/s/tPt) shows extensive use of the NSW LPI Base Map already in use as a source for OSM data. 

The team will use all available imagery sources to help to confirm alignment of  streets. 
Identifying streets missing names can be done simply by using custom paint styles in JOSM. 

- [Streets Have No Names](https://josm.openstreetmap.de/josmfile?page=Styles/Noname&zip=1)
- [FIXME Highlights Warnings](https://josm.openstreetmap.de/josmfile?page=Styles/Fixme&zip=1)

## Changeset Comments
The team will use changeset comments consistent with [OSM Changeset Guidelines](http://wiki.openstreetmap.org/wiki/Good_changeset_comments)
The team will also include a source:name=* tag (i.e.=NSW LPI Base Map) so the source of the name is clear.

**Comment by andrewharvey** [comment]
As pointed out at https://lists.openstreetmap.org/pipermail/talk-au/2017-December/011574.html, to be consistent with current tagging, it should be `source:name` and not `name:source`.

**Comment by jharpster** [comment]
Thanks for the feedback @andrewharvey

**Comment by andrewharvey** [comment]
I'm seeing a lot of changes of street names from the Microsoft Open Maps team recently, like https://osmcha.mapbox.com/changesets/61847421/

I'm concerned as many names have been changed without:

1. Checking with the original mapper who added the name
2. Checking street sign names from Mapillary/OpenStreetCam

Especially more concerning when it was tagged as survey, which should have higher weighting and priority than the LPI Base Map.

The LPI Basemap is not the gospel, the name tag should have what the street sign says, and while many of these are errors in OSM and you've been correcting them, I feel you should be going through the due diligence of checking Mapillary etc first and checking with the mapper via a changeset comment first.

**Comment by andrewharvey** [comment]
For example https://www.openstreetmap.org/changeset/50908854 a changeset comment on the changeset that added the previous name was able to confirm the situation on the ground.

**Comment by BrackoNe** [comment]
Hey Andrew,

Thanks for sharing this with us.
Just to be on the same page with you, please note that we are not using LPI as only source for determine whether we should change name or not. We are using multiple sources and after these sources gives us a hint - we are going straight to this position and checking with LPI.

We are not aware what name is in LPI all the way we navigate to it's position. Oisin talked about it in his session in Milan which is available online to look at it on demand.

It is always nice to talk with you,
Nemanja

**Comment by BrackoNe** [comment]
![image](https://user-images.githubusercontent.com/8583745/44404150-8dd33600-a556-11e8-927f-2796f2b983e3.png)
I have talked with Miroslav about this edit. He used Mapillary, and this is one of the rare situations when there is coverage.

**Comment by BrackoNe** [comment]
![image](https://user-images.githubusercontent.com/8583745/44404150-8dd33600-a556-11e8-927f-2796f2b983e3.png)
I have talked with Miroslav about this edit. He used Mapillary, and this is one of the rare situations when there is coverage.

So, most of these "survay" tags are acctualy fake. This is just cover for users if someone wants to ask about their work. I'm **not telling** that all users are doing that, but some of they do.

**Comment by BrackoNe** [comment]
Dear @andrewharvey,

I have found planty of the examples where "local" editors used "survay" or "signpost" as a source for adding names.
Here you can find one more example of the same issue:
https://www.openstreetmap.org/#map=16/-34.72880065725041/149.93797431339146

**Munro Road** should be **Graham Lane** and it is obvious that user continued to map road after he finished first part of **Munro Road**. So it is nonsense to spend additional valeuble time to contact the user if it is so obvious (even there is no Mapillary) that he/she put this tag without the reason. Two different sources that we are using shows this street should be named as **Graham Lane**.

Best Regards,
Nemanja
