### ISSUE TITLE
Fix Mini-Roundabouts

### ISSUE THREAD

**Issue by jharpster** [Microsoft/Open-Maps#7]
The goal of this task is to model min-roundabouts consistent with the [Australian tagging guidelines.](http://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines#Roundabouts)

This overpass query will identify nodes tagged as mini-roundabouts. 
https://overpass-turbo.eu/s/tUh.

![image](https://user-images.githubusercontent.com/224853/34184302-d7969988-e4d3-11e7-9203-0aeb6b457d7d.png)

Suggested Process: 

- Open over-pass turbo and use script listed above. 
- Click at the point and click at `Node` link to open new tab with feature that needs to be edited
- Edit data in either JOSM/ID Editor (iD is recommended for this task)
- Delete `highway:mini_roundabout` tag from junction using 
![image](https://user-images.githubusercontent.com/8978565/34225313-df2c2cce-e57a-11e7-80bc-3b7fba495c8b.png) button
- Use right click at the node in the middle of junction
![image](https://user-images.githubusercontent.com/8978565/34225418-454677bc-e57b-11e7-8adb-a57a13901f9b.png)
- Use `Split` function from contextual menu by clicking at 
![image](https://user-images.githubusercontent.com/8978565/34225488-87e86580-e57b-11e7-9d2e-d2689f86c9eb.png) button
- Right click at the same node again and use `Disconnect` function by clicking at
![image](https://user-images.githubusercontent.com/8978565/34225548-b17bea02-e57b-11e7-8729-85922b8220b1.png) button
- Now make some empty space for new roundabout like it is presented here: 
![image](https://user-images.githubusercontent.com/8978565/34226016-3591d6fc-e57d-11e7-9d1b-19009f458164.png)
- Begin inserting the circular features by mapping simple rectangle: 
![image](https://user-images.githubusercontent.com/8978565/34226080-6e9d7410-e57d-11e7-8bfa-e5791d77ef08.png)
- Right click at the way of that new rectangle (click in the middle of two nodes) and use `Circularize` function by clicking 
![image](https://user-images.githubusercontent.com/8978565/34226151-a5c0e0f8-e57d-11e7-9b43-55d2efd712f2.png)
 button
- If necessary, move roundabout to center it with imagery (
![image](https://user-images.githubusercontent.com/8978565/34226222-dfa61496-e57d-11e7-9563-976a3bf5b205.png)
 icon from contextual menu) and adding correct tag to geometry:
- highway=* 
- junction=roundabout 
- Each entry and exit way should join the roundabout at a separate node. 
- surface=* (where possible from Aerial Imagery) 
- name=* (IF there is a name specific to the junction add) 
- maxspeed=* (If possible from a corroborating source, if not leave it) 
- No need to add oneway=yes tag, as this is implied by the junction=roundabout tag. **IF** you are drawing roundabout from left to right. If you don’t, you have to put oneway tag.
 - Sources to check: Aerial Imagery, GPS tracks, Strava

**Comment by FrakGart** [comment]
Need to also fix any admin boundaries that were using the highway ways.

eg: Don't do this:
http://www.openstreetmap.org/changeset/54848378
